server:
  port: 8099
api:
    base-path: /api/v1
spring:
  messages:
    basename: i18n/messages
  quartz:
    jdbc:
      schema: classpath:quartz-schema.sql
      initialize-schema: always
    job-store-type: jdbc
    properties:
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.useProperties: false
      org.quartz.jobStore.tablePrefix: inventory.QRTZ_
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 5000
  main:
    lazy-initialization: false
  profiles:
    active: dev
auth:
  signing-token: ILOveGOD
  token-expiration: 1
  use-random: false
app:
  page:
    max: 40000